# Generated by Django 4.2.6 on 2024-03-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_art_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', verbose_name='Картина'),
        ),
    ]
