# Generated by Django 4.2.6 on 2024-03-05 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_art_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='uploaded_files/', verbose_name='Картина'),
        ),
    ]
