# Generated by Django 4.2.6 on 2024-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_art_uploaded_at_alter_art_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='main/static/DigitalHermitag/img/', verbose_name='Картина'),
        ),
    ]
