# Generated by Django 4.2.6 on 2024-03-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_art_exh_id_remove_art_uploaded_at_art_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='profile_name',
            field=models.CharField(default='anonymous', max_length=250, verbose_name='Имя профиля'),
        ),
    ]
