# Generated by Django 4.2.6 on 2024-03-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_art_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='profile_name',
            new_name='author',
        ),
    ]
