# Generated by Django 4.2.6 on 2024-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_profile_name_art_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='author',
            field=models.CharField(blank=True, default='anonymous', max_length=250, verbose_name='Имя профиля'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_file',
            field=models.ImageField(upload_to='uploaded_images/', verbose_name='Картина'),
        ),
    ]
